version: 2.1

parameters:
  front:
    type: boolean
    default: false

orbs:
  node: circleci/node@6.3.0

executors:
  default:
    working_directory: ~/project
    docker:
      - image: cimg/base:stable

workflows:
  version: 2
  setup-and-test:
    when: <<parameters.front>>
    jobs:
      - step:
          name: echo
          command: echo "frontのコード変更を検知"
